format = """
$cmd_duration\
$directory
$character\
"""

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "black bg:yellow"
format = "[ $duration ]($style)[\ue0b0 ](yellow bg:blue)"

[directory]
style = "black bg:blue"
format = "[$path ]($style)[\ue0b0](blue)"
truncation_length = 3
truncation_symbol = ".../"